services:
  db:
    image: postgres:latest
    container_name: fishdb
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: postgre
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: comp_club_app
    environment:
      - POSTGRES_DB=postgre
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=postgre
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8501:8501"
    depends_on:
      - db
    volumes:
      - .:/app
